<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class DocsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 17;

    public static function getMap(): array
    {
        $map = [
            'PROCEDURA' => new ReferenceField(
                'PROCEDURA', 
                DocsProcedurePropertyValuesTable::class, 
                ['=this.PROCEDURA' => 'ref.IBLOCK_ELEMENT_NAME']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
