<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class CarsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [
            'PROTSEDURY' => new ReferenceField(
                'PROTSEDURY', 
                CarCityPropertyValuesTable::class, 
                ['=this.CITY_ID' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
